from abc import ABC
from application.domain.order import Order
from typing import List


class OrderRepository(ABC):
    def get_order_by_id(self, order_id: str) -> Order: ...
    def create_order(self, order: Order): ...
    def get_all_orders(self) -> List[Order]: ...
    def update_order(self, order: Order): ...
